app = "goit-pythonweb-hw-12"
primary_region = "fra"

[build]
  # Uses Dockerfile at repo root

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[metrics]
  port = 9091
  path = "/metrics"
